import type { Metadata } from "next";
import { Space_Grotesk, Inter } from "next/font/google";
import Script from "next/script";
import { ThemeProvider } from "@/components/theme-provider";
import { SiteShell } from "@/components/site-shell";
import "./globals.css";

const space = Space_Grotesk({ subsets: ["latin"], variable: "--font-display", display: "swap" });
const inter = Inter({ subsets: ["latin"], variable: "--font-body", display: "swap" });
export const metadata: Metadata = { metadataBase: new URL("https://eduardoferreira.space"), title: { default: "Eduardo Ferreira | Infraestrutura, redes e tecnologia", template: "%s | Eduardo Ferreira" }, description: "Técnico de TI em Fortaleza, com atuação em infraestrutura, redes, suporte, virtualização e automação.", icons: { icon: [{ url: "/favicon.ico", type: "image/x-icon" }, { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" }, { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" }, { url: "/favicon-192x192.png", sizes: "192x192", type: "image/png" }, { url: "/favicon-512x512.png", sizes: "512x512", type: "image/png" }], apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }] }, openGraph: { type: "website", locale: "pt_BR", siteName: "Eduardo Ferreira", title: "Eduardo Ferreira | Infraestrutura, redes e tecnologia", description: "Técnico de TI em Fortaleza, com atuação em infraestrutura, redes, suporte, virtualização e automação.", url: "https://eduardoferreira.space" }, robots: { index: true, follow: true } };
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) { const person = { "@context": "https://schema.org", "@type": "Person", name: "Carlos Eduardo Rodrigues Ferreira", url: "https://eduardoferreira.space", jobTitle: "Técnico de TI", description: "Técnico de TI com atuação em suporte, infraestrutura, redes, virtualização e automação.", address: { "@type": "PostalAddress", addressLocality: "Fortaleza", addressRegion: "CE", addressCountry: "BR" }, sameAs: ["https://github.com/Forevit", "https://www.linkedin.com/in/carloseduardorodriguesferreira/"] }; return <html lang="pt-BR" data-theme="dark"><body className={`${space.variable} ${inter.variable}`}><ThemeProvider><SiteShell>{children}</SiteShell></ThemeProvider><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(person) }} /><Script async src="https://www.googletagmanager.com/gtag/js?id=G-B4YV9LLZKP" strategy="afterInteractive" /><Script id="google-analytics" strategy="afterInteractive">{`window.dataLayer = window.dataLayer || []; function gtag(){window.dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-B4YV9LLZKP');`}</Script></body></html>; }
